export const judge = {
  title: 'Glasanje',
  subtitle: 'Ocijenite svaku ekipu od 1 do 10 po oba kriterija.',
  remaining: (n: number) => (n === 1 ? 'Preostala 1 ocjena' : `Preostalo ocjena: ${n}`),
  allDone: 'Sve ocjene su poslane. Hvala!',
  filterRemaining: 'Preostale',
  filterAll: 'Sve ekipe',
  noTeams: 'Administrator još nije unio nijednu ekipu.',
  noRemaining: 'Nema više ekipa koje čekaju Vašu ocjenu.',
  pick: 'Odaberite ocjenu',
  submit: (points: number) => `Pošalji ocjenu ${points}`,
  submitDisabled: 'Pošalji ocjenu',
  submitting: 'Slanje…',
  submitted: 'Poslano',
  // Submission is final for the judge, so the screen has to say so before the tap.
  finalNotice: 'Poslana ocjena se ne može mijenjati. Za ispravku se obratite administratoru.',
  submittedAt: (time: string) => `Poslano u ${time}`,
  bib: (n: number) => `Startni broj ${n}`,
  team: 'Ekipa',
} as const;
